import { getImageDimensions } from "./imageDimensions";

export type ProductCard = {
  cardType: string;
  brand: string;
  brandCluster: string;
  heroTitle: string;
  heroSubtitle: string;
  submodelCode: string;
  engineModel: string;
  gearboxModel: string;
  productBand: "light_truck" | "medium_truck" | "heavy_truck" | "mini_truck";
  techStatus: "researched" | "partial";
  applicableVehicleCodes: string[];
  applicableMarkets: string[];
  displayPartFamilies: string[];
  trustSignal: string;
  imageDirection: string;
  contentBlocks: string[];
  ctaText: string;
  internalDataSource: string;
  heroImage: string;
  heroImageAlt: string;
  heroImageWidth: number;
  heroImageHeight: number;
};

const platformImageMap = {
  light_truck: "/images/Engine-Parts.png",
  medium_truck: "/images/Engine-Parts.png",
  heavy_truck: "/images/Engine-Parts.png",
  mini_truck: "/images/Engine-Parts.png",
} as const;

const rows = [
  {
    cardType: "engine_family",
    brand: "Foton",
    brandCluster: "Aumark",
    heroTitle: "ISF3.8s5168",
    heroSubtitle: "Aumark | 1128VGPEK-F2DA03 | light truck",
    submodelCode: "1128VGPEK-F2DA03",
    engineModel: "Cummins ISF3.8s5168",
    gearboxModel: "ZF EcoLite 6S600",
    productBand: "light_truck",
    techStatus: "researched",
    applicableVehicleCodes: "1128VGPEK-F2DA03",
    applicableMarkets: "中国(927) / 亚中亚(524) / 俄罗斯联邦(81)",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Engine/gearbox platform mapped from public spec pages and market listings",
    imageDirection: "Use engine or gearbox hero image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "tech_research_table_3 + catalog_launch_table_6",
  },
  {
    cardType: "engine_family",
    brand: "Foton",
    brandCluster: "Aumark",
    heroTitle: "ISF3.8",
    heroSubtitle: "Aumark | 1078VEJEA-F1DA01 | light truck",
    submodelCode: "1078VEJEA-F1DA01",
    engineModel: "Cummins ISF3.8",
    gearboxModel: "ZF 6S6000",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "1078VEJEA-F1DA01",
    applicableMarkets: "菲律宾(900) / 哥伦比亚(281)",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Engine/gearbox platform mapped from public spec pages and market listings",
    imageDirection: "Use engine or gearbox hero image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "tech_research_table_3 + catalog_launch_table_6",
  },
  {
    cardType: "engine_family",
    brand: "Foton",
    brandCluster: "Aumark",
    heroTitle: "4J28TC",
    heroSubtitle: "Aumark | C010285P001E001 | light truck",
    submodelCode: "C010285P001E001",
    engineModel: "Quanchai 4J28TC",
    gearboxModel: "ZF 5S408",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "C010285P001E001",
    applicableMarkets: "亚中亚(561) / 中国(548) / 中国香港(23)",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Engine/gearbox platform mapped from public spec pages and market listings",
    imageDirection: "Use engine or gearbox hero image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "tech_research_table_3 + catalog_launch_table_6",
  },
  {
    cardType: "engine_family",
    brand: "Foton",
    brandCluster: "Auman",
    heroTitle: "ISGe5-430",
    heroSubtitle: "Auman | 4189SLFKA-B2TA0100 | heavy truck",
    submodelCode: "4189SLFKA-B2TA0100",
    engineModel: "Cummins ISGe5-430",
    gearboxModel: "FAST 12JSD180TA",
    productBand: "heavy_truck",
    techStatus: "partial",
    applicableVehicleCodes: "4189SLFKA-B2TA0100",
    applicableMarkets: "中国(3674) / 俄罗斯联邦(1612) / 亚中亚(412)",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Engine/gearbox platform mapped from public spec pages and market listings",
    imageDirection: "Use engine or gearbox hero image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "tech_research_table_3 + catalog_launch_table_6",
  },
  {
    cardType: "engine_family",
    brand: "Foton",
    brandCluster: "Auman",
    heroTitle: "ISGe5-460",
    heroSubtitle: "Auman | 4189SLFKA-B2TA0200 | heavy truck",
    submodelCode: "4189SLFKA-B2TA0200",
    engineModel: "Cummins ISGe5-460",
    gearboxModel: "FAST 12JSD180TA",
    productBand: "heavy_truck",
    techStatus: "partial",
    applicableVehicleCodes: "4189SLFKA-B2TA0200",
    applicableMarkets: "俄罗斯联邦(609) / 中国(388) / 亚中亚(236)",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Engine/gearbox platform mapped from public spec pages and market listings",
    imageDirection: "Use engine or gearbox hero image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "tech_research_table_3 + catalog_launch_table_6",
  },
  {
    cardType: "engine_family",
    brand: "Foton",
    brandCluster: "Auman",
    heroTitle: "X13NS5-560",
    heroSubtitle: "Auman | 4259SMFKB-C1TA0100 | heavy truck",
    submodelCode: "4259SMFKB-C1TA0100",
    engineModel: "Cummins X13NS5-560",
    gearboxModel: "ZF 12TX2621TD",
    productBand: "heavy_truck",
    techStatus: "researched",
    applicableVehicleCodes: "4259SMFKB-C1TA0100",
    applicableMarkets: "中国香港(1091)",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Engine/gearbox platform mapped from public spec pages and market listings",
    imageDirection: "Use engine or gearbox hero image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "tech_research_table_3 + catalog_launch_table_6",
  },
  {
    cardType: "engine_family",
    brand: "Foton",
    brandCluster: "Ollin",
    heroTitle: "4J28TC",
    heroSubtitle: "Ollin | 1044V9JD4-F1DA10 | light truck",
    submodelCode: "1044V9JD4-F1DA10",
    engineModel: "Quanchai 4J28TC",
    gearboxModel: "Wanliyang 5MT",
    productBand: "light_truck",
    techStatus: "researched",
    applicableVehicleCodes: "1044V9JD4-F1DA10",
    applicableMarkets: "哥伦比亚(1728)",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Engine/gearbox platform mapped from public spec pages and market listings",
    imageDirection: "Use engine or gearbox hero image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "tech_research_table_3 + catalog_launch_table_6",
  },
  {
    cardType: "engine_family",
    brand: "Foton",
    brandCluster: "Ollin",
    heroTitle: "F3.8NS6B170",
    heroSubtitle: "Ollin | 1108VEJED-FADA04 | light truck",
    submodelCode: "1108VEJED-FADA04",
    engineModel: "Foton Cummins F3.8NS6B170",
    gearboxModel: "FAST 8JS75TC",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "1108VEJED-FADA04",
    applicableMarkets: "哥伦比亚(1222) / 菲律宾(103) / 中国香港(19)",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Engine/gearbox platform mapped from public spec pages and market listings",
    imageDirection: "Use engine or gearbox hero image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "tech_research_table_3 + catalog_launch_table_6",
  },
  {
    cardType: "engine_family",
    brand: "Foton",
    brandCluster: "Ollin",
    heroTitle: "4J28TC",
    heroSubtitle: "Ollin | C010259N001E001 | light truck",
    submodelCode: "C010259N001E001",
    engineModel: "Quanchai 4J28TC",
    gearboxModel: "Qingshan 5G32",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "C010259N001E001",
    applicableMarkets: "哥伦比亚(1020)",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Engine/gearbox platform mapped from public spec pages and market listings",
    imageDirection: "Use engine or gearbox hero image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "tech_research_table_3 + catalog_launch_table_6",
  },
  {
    cardType: "engine_family",
    brand: "Foton",
    brandCluster: "Xiangling",
    heroTitle: "DAM15R",
    heroSubtitle: "Xiangling | 1030V4JV2-BHDA11 | mini truck",
    submodelCode: "1030V4JV2-BHDA11",
    engineModel: "Dongan DAM15R",
    gearboxModel: "Dongan DAT18R",
    productBand: "mini_truck",
    techStatus: "partial",
    applicableVehicleCodes: "1030V4JV2-BHDA11",
    applicableMarkets: "中国香港(2112) / 中国(200)",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Engine/gearbox platform mapped from public spec pages and market listings",
    imageDirection: "Use engine or gearbox hero image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "tech_research_table_3 + catalog_launch_table_6",
  },
  {
    cardType: "engine_family",
    brand: "Foton",
    brandCluster: "Xiangling",
    heroTitle: "DAM15R",
    heroSubtitle: "Xiangling | 1030V4JV2-BHDA07 | mini truck",
    submodelCode: "1030V4JV2-BHDA07",
    engineModel: "Dongan DAM15R",
    gearboxModel: "Dongan DAT18R",
    productBand: "mini_truck",
    techStatus: "partial",
    applicableVehicleCodes: "1030V4JV2-BHDA07",
    applicableMarkets: "哥伦比亚(1300) / 秘鲁(219) / 秘鲁共和国(32)",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Engine/gearbox platform mapped from public spec pages and market listings",
    imageDirection: "Use engine or gearbox hero image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "tech_research_table_3 + catalog_launch_table_6",
  },
  {
    cardType: "engine_family",
    brand: "Foton",
    brandCluster: "Xiangling",
    heroTitle: "DAM15R",
    heroSubtitle: "Xiangling | 1030V4JV2-BHDA01 | mini truck",
    submodelCode: "1030V4JV2-BHDA01",
    engineModel: "Dongan DAM15R",
    gearboxModel: "Dongan DAT18R",
    productBand: "mini_truck",
    techStatus: "partial",
    applicableVehicleCodes: "1030V4JV2-BHDA01",
    applicableMarkets: "中国香港(1295) / 玻利维亚(262) / 中国(2)",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Engine/gearbox platform mapped from public spec pages and market listings",
    imageDirection: "Use engine or gearbox hero image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "tech_research_table_3 + catalog_launch_table_6",
  },
  {
    cardType: "engine_family",
    brand: "Foton",
    brandCluster: "Forland",
    heroTitle: "4W12M",
    heroSubtitle: "Forland | 1036V5JV5-AADA024Q | light truck",
    submodelCode: "1036V5JV5-AADA024Q",
    engineModel: "Beinei 4W12M",
    gearboxModel: "",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "1036V5JV5-AADA024Q",
    applicableMarkets: "菲律宾(1000)",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Engine/gearbox platform mapped from public spec pages and market listings",
    imageDirection: "Use engine or gearbox hero image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "tech_research_table_3 + catalog_launch_table_6",
  },
  {
    cardType: "engine_family",
    brand: "Foton",
    brandCluster: "Forland",
    heroTitle: "LJ469Q-1AE9",
    heroSubtitle: "Forland | 1036V4AV5-D2ZA054Q | light truck",
    submodelCode: "1036V4AV5-D2ZA054Q",
    engineModel: "Liuzhou Wuling LJ469Q-1AE9",
    gearboxModel: "Mengwo MR513B",
    productBand: "light_truck",
    techStatus: "researched",
    applicableVehicleCodes: "1036V4AV5-D2ZA054Q",
    applicableMarkets: "南非(290)",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Engine/gearbox platform mapped from public spec pages and market listings",
    imageDirection: "Use engine or gearbox hero image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "tech_research_table_3 + catalog_launch_table_6",
  },
  {
    cardType: "engine_family",
    brand: "Foton",
    brandCluster: "Forland",
    heroTitle: "LJ469Q-1AE9",
    heroSubtitle: "Forland | 1036V5JV5-D1ZA064Q | light truck",
    submodelCode: "1036V5JV5-D1ZA064Q",
    engineModel: "Liuzhou Wuling LJ469Q-1AE9",
    gearboxModel: "Mengwo 5MT",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "1036V5JV5-D1ZA064Q",
    applicableMarkets: "南非(246)",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Engine/gearbox platform mapped from public spec pages and market listings",
    imageDirection: "Use engine or gearbox hero image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "tech_research_table_3 + catalog_launch_table_6",
  },
  {
    cardType: "engine_family",
    brand: "DFSK",
    brandCluster: "DFSK K Series",
    heroTitle: "DK12-10",
    heroSubtitle: "DFSK K Series | K01S | mini truck",
    submodelCode: "K01S",
    engineModel: "DFSK DK12-10",
    gearboxModel: "DFSK 5MT",
    productBand: "mini_truck",
    techStatus: "partial",
    applicableVehicleCodes: "K01S",
    applicableMarkets: "危地马拉 / 拉美",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Competitor model platform mapped from public export-facing product pages",
    imageDirection: "Use engine or complete cargo mini-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "DFSK",
    brandCluster: "DFSK K Series",
    heroTitle: "DK13-09",
    heroSubtitle: "DFSK K Series | K02S | mini truck",
    submodelCode: "K02S",
    engineModel: "DFSK DK13-09",
    gearboxModel: "DFSK 5MT",
    productBand: "mini_truck",
    techStatus: "partial",
    applicableVehicleCodes: "K02S",
    applicableMarkets: "危地马拉 / 拉美",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Competitor model platform mapped from public export-facing product pages",
    imageDirection: "Use engine or complete cargo mini-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "DFSK",
    brandCluster: "DFSK K Series",
    heroTitle: "DK15-06",
    heroSubtitle: "DFSK K Series | K05S | mini truck",
    submodelCode: "K05S",
    engineModel: "DFSK DK15-06",
    gearboxModel: "DFSK 5MT",
    productBand: "mini_truck",
    techStatus: "partial",
    applicableVehicleCodes: "K05S",
    applicableMarkets: "危地马拉 / 拉美",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Competitor model platform mapped from public export-facing product pages",
    imageDirection: "Use engine or complete cargo mini-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "Wuling",
    brandCluster: "Wuling Formo Max",
    heroTitle: "LAR",
    heroSubtitle: "Wuling Formo Max | Standard | mini truck",
    submodelCode: "Formo Max Standard",
    engineModel: "SGMW LAR",
    gearboxModel: "SGMW 5MT",
    productBand: "mini_truck",
    techStatus: "partial",
    applicableVehicleCodes: "Formo Max Standard",
    applicableMarkets: "印尼 / 东南亚",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Competitor model platform mapped from official commercial vehicle product pages",
    imageDirection: "Use engine or complete vehicle image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "Wuling",
    brandCluster: "Wuling Formo Max",
    heroTitle: "LAR",
    heroSubtitle: "Wuling Formo Max | AC | mini truck",
    submodelCode: "Formo Max AC",
    engineModel: "SGMW LAR",
    gearboxModel: "SGMW 5MT",
    productBand: "mini_truck",
    techStatus: "partial",
    applicableVehicleCodes: "Formo Max AC",
    applicableMarkets: "印尼 / 东南亚",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Competitor model platform mapped from official commercial vehicle product pages",
    imageDirection: "Use engine or complete vehicle image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "Wuling",
    brandCluster: "Wuling Formo Max",
    heroTitle: "LAR",
    heroSubtitle: "Wuling Formo Max | Pickup | mini truck",
    submodelCode: "Formo Max Pickup",
    engineModel: "SGMW LAR",
    gearboxModel: "SGMW 5MT",
    productBand: "mini_truck",
    techStatus: "partial",
    applicableVehicleCodes: "Formo Max Pickup",
    applicableMarkets: "印尼 / 东南亚",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Competitor model platform mapped from official commercial vehicle product pages",
    imageDirection: "Use engine or complete vehicle image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "JAC",
    brandCluster: "JAC Kangda X5",
    heroTitle: "全柴Q23A-82E60",
    heroSubtitle: "JAC Kangda X5 | HFC5040XXYPV3K1B3S | mini truck",
    submodelCode: "HFC5040XXYPV3K1B3S",
    engineModel: "Quanchai Q23A-82E60",
    gearboxModel: "Xingrui LC5T28",
    productBand: "mini_truck",
    techStatus: "partial",
    applicableVehicleCodes: "HFC5040XXYPV3K1B3S",
    applicableMarkets: "中国公开公告 / 微卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete entry truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "JAC",
    brandCluster: "JAC Kangda X6",
    heroTitle: "HFC4GB3-3E",
    heroSubtitle: "JAC Kangda X6 | HFC1036PV3E3C1S-2 | mini truck",
    submodelCode: "HFC1036PV3E3C1S-2",
    engineModel: "JAC HFC4GB3-3E",
    gearboxModel: "JAC 6MT",
    productBand: "mini_truck",
    techStatus: "partial",
    applicableVehicleCodes: "HFC1036PV3E3C1S-2",
    applicableMarkets: "中国公开公告 / 微卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete entry truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "JAC",
    brandCluster: "JAC Kangda X6",
    heroTitle: "云内D20TCIF13",
    heroSubtitle: "JAC Kangda X6 | HFC5040XXYPV4K1C1S | mini truck",
    submodelCode: "HFC5040XXYPV4K1C1S",
    engineModel: "Yunnei D20TCIF13",
    gearboxModel: "Xingrui ML532A",
    productBand: "mini_truck",
    techStatus: "partial",
    applicableVehicleCodes: "HFC5040XXYPV4K1C1S",
    applicableMarkets: "中国公开公告 / 微卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete entry truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "JAC",
    brandCluster: "JAC Shuailing H330",
    heroTitle: "HFC4DA1-2D",
    heroSubtitle: "JAC Shuailing H330 | HFC5043XXYP71K2C2V | light truck",
    submodelCode: "HFC5043XXYP71K2C2V",
    engineModel: "JAC HFC4DA1-2D",
    gearboxModel: "Liuan LC6T450M1",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "HFC5043XXYP71K2C2V",
    applicableMarkets: "中国公开公告 / 轻卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete light-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "JAC",
    brandCluster: "JAC Shuailing H330",
    heroTitle: "ISF3.8s5154",
    heroSubtitle: "JAC Shuailing H330 | HFC5043CCYP71K3C2V | light truck",
    submodelCode: "HFC5043CCYP71K3C2V",
    engineModel: "Cummins ISF3.8s5154",
    gearboxModel: "FAST 8JS75TC",
    productBand: "light_truck",
    techStatus: "researched",
    applicableVehicleCodes: "HFC5043CCYP71K3C2V",
    applicableMarkets: "中国公开公告 / 轻卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public product page",
    imageDirection: "Use engine or complete light-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "JAC",
    brandCluster: "JAC Junling V7",
    heroTitle: "ISF3.8s5154",
    heroSubtitle: "JAC Junling V7 | HFC5120XXYP91K1D4V | light truck",
    submodelCode: "HFC5120XXYP91K1D4V",
    engineModel: "Cummins ISF3.8s5154",
    gearboxModel: "Liuan LC6T540B",
    productBand: "light_truck",
    techStatus: "researched",
    applicableVehicleCodes: "HFC5120XXYP91K1D4V",
    applicableMarkets: "中国公开公告 / 轻卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public product page",
    imageDirection: "Use engine or complete light-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "Dongfeng",
    brandCluster: "Dongfeng Captain T Series",
    heroTitle: "YC4F115-50",
    heroSubtitle: "Dongfeng Captain T Series | EQ1075S8CDF | light truck",
    submodelCode: "EQ1075S8CDF",
    engineModel: "Yuchai YC4F115-50",
    gearboxModel: "6J45T",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "EQ1075S8CDF",
    applicableMarkets: "海外经销公共平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from public parameter page and domestic light-truck listing",
    imageDirection: "Use engine or complete truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "Dongfeng",
    brandCluster: "Dongfeng Captain T Series",
    heroTitle: "YC4F115-50",
    heroSubtitle: "Dongfeng Captain T Series | EQ5041XXYTACD3AC | light truck",
    submodelCode: "EQ5041XXYTACD3AC",
    engineModel: "Yuchai YC4F115-50",
    gearboxModel: "6J45T",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "EQ5041XXYTACD3AC",
    applicableMarkets: "海外经销公共平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from public parameter page and domestic light-truck listing",
    imageDirection: "Use engine or complete truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "Dongfeng",
    brandCluster: "Dongfeng Captain T Series",
    heroTitle: "YC4F115-50",
    heroSubtitle: "Dongfeng Captain T Series | EQ1041TACDJ3AC | light truck",
    submodelCode: "EQ1041TACDJ3AC",
    engineModel: "Yuchai YC4F115-50",
    gearboxModel: "6J45T",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "EQ1041TACDJ3AC",
    applicableMarkets: "海外经销公共平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from public parameter page and domestic light-truck listing",
    imageDirection: "Use engine or complete truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "JAC",
    brandCluster: "JAC Junling V7",
    heroTitle: "ISF3.8s5154",
    heroSubtitle: "JAC Junling V7 | HFC5091XXYP91K1D1V | light truck",
    submodelCode: "HFC5091XXYP91K1D1V",
    engineModel: "Cummins ISF3.8s5154",
    gearboxModel: "Liuan LC6T540B",
    productBand: "light_truck",
    techStatus: "researched",
    applicableVehicleCodes: "HFC5091XXYP91K1D1V",
    applicableMarkets: "中国公开公告 / 轻卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public product page",
    imageDirection: "Use engine or larger cargo truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "JAC",
    brandCluster: "JAC Junling V7",
    heroTitle: "ISF3.8s5154",
    heroSubtitle: "JAC Junling V7 | HFC5120XXYP91K1D4V | light truck",
    submodelCode: "HFC5120XXYP91K1D4V",
    engineModel: "Cummins ISF3.8s5154",
    gearboxModel: "Liuan LC6T540B",
    productBand: "light_truck",
    techStatus: "researched",
    applicableVehicleCodes: "HFC5120XXYP91K1D4V",
    applicableMarkets: "中国公开公告 / 轻卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public product page",
    imageDirection: "Use engine or larger cargo truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "JAC",
    brandCluster: "JAC Geerfa A5L",
    heroTitle: "YCK05240-60",
    heroSubtitle: "JAC Geerfa A5L | HFC5181XXYP2K2A50CS | medium truck",
    submodelCode: "HFC5181XXYP2K2A50CS",
    engineModel: "Yuchai YCK05240-60",
    gearboxModel: "FAST 8MT",
    productBand: "medium_truck",
    techStatus: "partial",
    applicableVehicleCodes: "HFC5181XXYP2K2A50CS",
    applicableMarkets: "中国公开公告 / 中卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or larger cargo truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "JMC",
    brandCluster: "JMC Kaiyun Series",
    heroTitle: "JX493ZLQ5",
    heroSubtitle: "JMC Kaiyun Series | JX1041TG26 | light truck",
    submodelCode: "JX1041TG26",
    engineModel: "JMC JX493ZLQ5",
    gearboxModel: "JMC 5MT",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "JX1041TG26",
    applicableMarkets: "沙特 / 中东",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from public parameter page and domestic light-truck listing",
    imageDirection: "Use engine or utility truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "JMC",
    brandCluster: "JMC Kaiyun Series",
    heroTitle: "JX493ZLQ5",
    heroSubtitle: "JMC Kaiyun Series | JX1041TSG26 | light truck",
    submodelCode: "JX1041TSG26",
    engineModel: "JMC JX493ZLQ5",
    gearboxModel: "JMC 5MT",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "JX1041TSG26",
    applicableMarkets: "沙特 / 中东",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from public parameter page and domestic light-truck listing",
    imageDirection: "Use engine or utility truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "JMC",
    brandCluster: "JMC Kaiyun Series",
    heroTitle: "JX4D25A6L",
    heroSubtitle: "JMC Kaiyun Series | JX1045TG26 | light truck",
    submodelCode: "JX1045TG26",
    engineModel: "JMC JX4D25A6L",
    gearboxModel: "JMC 6MT",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "JX1045TG26",
    applicableMarkets: "沙特 / 中东",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from public parameter page and domestic light-truck listing",
    imageDirection: "Use engine or utility truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "Dongfeng",
    brandCluster: "Dongfeng Tuyi T3",
    heroTitle: "LJ4A16QG",
    heroSubtitle: "Dongfeng Tuyi T3 | EQ1034D60Q4D | light truck",
    submodelCode: "EQ1034D60Q4D",
    engineModel: "Liuzhou Wuling LJ4A16QG",
    gearboxModel: "Mengwo MG516",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "EQ1034D60Q4D",
    applicableMarkets: "中国公开公告 / 微卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or mini cargo truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "Dongfeng",
    brandCluster: "Dongfeng Tuyi T3",
    heroTitle: "LJ469Q-AEB",
    heroSubtitle: "Dongfeng Tuyi T3 | EQ1020D60Q3 | light truck",
    submodelCode: "EQ1020D60Q3",
    engineModel: "Liuzhou Wuling LJ469Q-AEB",
    gearboxModel: "Mengwo MR63",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "EQ1020D60Q3",
    applicableMarkets: "中国公开公告 / 微卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or mini cargo truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "Dongfeng",
    brandCluster: "Dongfeng Tuyi T3",
    heroTitle: "LJ4A16QG",
    heroSubtitle: "Dongfeng Tuyi T3 | EQ5030XXYD60Q4DAC | light truck",
    submodelCode: "EQ5030XXYD60Q4DAC",
    engineModel: "Liuzhou Wuling LJ4A16QG",
    gearboxModel: "Mengwo MG516",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "EQ5030XXYD60Q4DAC",
    applicableMarkets: "中国公开公告 / 微卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or mini cargo truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "JAC",
    brandCluster: "JAC Kangling H3",
    heroTitle: "云内D20TCIF16",
    heroSubtitle: "JAC Kangling H3 | HFC1041P23K2B3QS | light truck",
    submodelCode: "HFC1041P23K2B3QS",
    engineModel: "Yunnei D20TCIF16",
    gearboxModel: "Wanliyang WLY5TS32C",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "HFC1041P23K2B3QS",
    applicableMarkets: "中国公开公告 / 轻卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or entry truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "JAC",
    brandCluster: "JAC Kangling H3",
    heroTitle: "全柴Q23A-142E60",
    heroSubtitle: "JAC Kangling H3 | HFC5041CCYB23K1C7S | light truck",
    submodelCode: "HFC5041CCYB23K1C7S",
    engineModel: "Quanchai Q23A-142E60",
    gearboxModel: "Wanliyang WLY5TS32C",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "HFC5041CCYB23K1C7S",
    applicableMarkets: "中国公开公告 / 轻卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or entry truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "JAC",
    brandCluster: "JAC Kangling H5",
    heroTitle: "云内YN25PLUS160A",
    heroSubtitle: "JAC Kangling H5 | HFC5043CCYP31K1C7NS | light truck",
    submodelCode: "HFC5043CCYP31K1C7NS",
    engineModel: "Yunnei YN25PLUS160A",
    gearboxModel: "Liuan LC6T450B",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "HFC5043CCYP31K1C7NS",
    applicableMarkets: "中国公开公告 / 轻卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or entry truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "Sinotruk",
    brandCluster: "HOWO TX",
    heroTitle: "MC11.44-50",
    heroSubtitle: "HOWO TX | ZZ4187N361GE1 | heavy truck",
    submodelCode: "ZZ4187N361GE1",
    engineModel: "Sinotruk MC11.44-50",
    gearboxModel: "Sinotruk HW19712C",
    productBand: "heavy_truck",
    techStatus: "researched",
    applicableVehicleCodes: "ZZ4187N361GE1",
    applicableMarkets: "中国公开公告 / 重卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete tractor-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "Sinotruk",
    brandCluster: "HOWO TX",
    heroTitle: "MC11.40-50",
    heroSubtitle: "HOWO TX | ZZ3257N384HE1 | heavy truck",
    submodelCode: "ZZ3257N384HE1",
    engineModel: "Sinotruk MC11.40-50",
    gearboxModel: "Sinotruk HW10",
    productBand: "heavy_truck",
    techStatus: "researched",
    applicableVehicleCodes: "ZZ3257N384HE1",
    applicableMarkets: "中国公开公告 / 重卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete dump-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "Sinotruk",
    brandCluster: "HOWO TX",
    heroTitle: "MC07H.33-61",
    heroSubtitle: "HOWO TX | ZZ1257N56CGF1 | heavy truck",
    submodelCode: "ZZ1257N56CGF1",
    engineModel: "Sinotruk MC07H.33-61",
    gearboxModel: "Sinotruk 8MT",
    productBand: "heavy_truck",
    techStatus: "partial",
    applicableVehicleCodes: "ZZ1257N56CGF1",
    applicableMarkets: "中国公开公告 / 重卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete cargo heavy-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "SHACMAN",
    brandCluster: "Delong X3000",
    heroTitle: "WP12.430E50",
    heroSubtitle: "Delong X3000 | SX4250XC4 | heavy truck",
    submodelCode: "SX4250XC4",
    engineModel: "Weichai WP12.430E50",
    gearboxModel: "FAST 12JSD200TA-B",
    productBand: "heavy_truck",
    techStatus: "partial",
    applicableVehicleCodes: "SX4250XC4",
    applicableMarkets: "中国公开公告 / 重卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete heavy-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "SHACMAN",
    brandCluster: "Delong F3000",
    heroTitle: "WP12.375E50",
    heroSubtitle: "Delong F3000 | SX5250ZLJDB424A | heavy truck",
    submodelCode: "SX5250ZLJDB424A",
    engineModel: "Weichai WP12.375E50",
    gearboxModel: "FAST 12JSD180T",
    productBand: "heavy_truck",
    techStatus: "partial",
    applicableVehicleCodes: "SX5250ZLJDB424A",
    applicableMarkets: "中国公开公告 / 重卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete heavy-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "SHACMAN",
    brandCluster: "Delong H3000",
    heroTitle: "WP10.340E53",
    heroSubtitle: "Delong H3000 | SX1189LA1F1C | heavy truck",
    submodelCode: "SX1189LA1F1C",
    engineModel: "Weichai WP10.340E53",
    gearboxModel: "FAST 10JSD140T",
    productBand: "heavy_truck",
    techStatus: "partial",
    applicableVehicleCodes: "SX1189LA1F1C",
    applicableMarkets: "国际重卡渠道",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from public parameter page and domestic heavy-truck listing",
    imageDirection: "Use engine or complete heavy-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "FAW",
    brandCluster: "FAW J6P",
    heroTitle: "CA6DM2-46E52",
    heroSubtitle: "FAW J6P | CA4250P66K24T1A1E5 | heavy truck",
    submodelCode: "CA4250P66K24T1A1E5",
    engineModel: "FAW CA6DM2-46E52",
    gearboxModel: "FAW CA12TAX210M",
    productBand: "heavy_truck",
    techStatus: "partial",
    applicableVehicleCodes: "CA4250P66K24T1A1E5",
    applicableMarkets: "中国公开公告 / 重卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete heavy-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "FAW",
    brandCluster: "FAW J6P",
    heroTitle: "CA6DK1-32E5",
    heroSubtitle: "FAW J6P | CA1250P62K1L7T3E6 | heavy truck",
    submodelCode: "CA1250P62K1L7T3E6",
    engineModel: "FAW CA6DK1-32E5",
    gearboxModel: "FAST 10JSD140T",
    productBand: "heavy_truck",
    techStatus: "partial",
    applicableVehicleCodes: "CA1250P62K1L7T3E6",
    applicableMarkets: "中国一汽国际重卡渠道",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from public product page and domestic heavy-truck listing",
    imageDirection: "Use engine or complete heavy-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "FAW",
    brandCluster: "FAW J6P",
    heroTitle: "CA6DM3-55E52",
    heroSubtitle: "FAW J6P | CA3250P66K2L1BT1E6 | heavy truck",
    submodelCode: "CA3250P66K2L1BT1E6",
    engineModel: "FAW CA6DM3-55E52",
    gearboxModel: "FAST 12JSD220TA",
    productBand: "heavy_truck",
    techStatus: "partial",
    applicableVehicleCodes: "CA3250P66K2L1BT1E6",
    applicableMarkets: "中国一汽国际重卡渠道",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from public product page and domestic heavy-truck listing",
    imageDirection: "Use engine or complete heavy-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "competitor_export_model_table_9 + competitor_subbrand_table_8",
  },
  {
    cardType: "engine_family",
    brand: "Dongfeng",
    brandCluster: "Dongfeng Dolica D6",
    heroTitle: "全柴Q25N-152E60",
    heroSubtitle: "Dongfeng Dolica D6 | EQ5040CCY7TDFDAC | light truck",
    submodelCode: "EQ5040CCY7TDFDAC",
    engineModel: "Quanchai Q25N-152E60",
    gearboxModel: "Wanliyang 6TS40",
    productBand: "light_truck",
    techStatus: "researched",
    applicableVehicleCodes: "EQ5040CCY7TDFDAC",
    applicableMarkets: "中国公开公告 / 轻卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete light-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "360che public listing + domestic replacement mapping",
  },
  {
    cardType: "engine_family",
    brand: "Dongfeng",
    brandCluster: "Dongfeng Dolica D6",
    heroTitle: "东风ZD25D16-6D",
    heroSubtitle: "Dongfeng Dolica D6 | EQ5042XXY3CDFAC | light truck",
    submodelCode: "EQ5042XXY3CDFAC",
    engineModel: "Dongfeng ZD25D16-6D",
    gearboxModel: "FAST C6J45T",
    productBand: "light_truck",
    techStatus: "researched",
    applicableVehicleCodes: "EQ5042XXY3CDFAC",
    applicableMarkets: "中国公开公告 / 轻卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete light-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "360che public listing + domestic replacement mapping",
  },
  {
    cardType: "engine_family",
    brand: "Dongfeng",
    brandCluster: "Dongfeng Dolica D6",
    heroTitle: "玉柴YCY24155-61",
    heroSubtitle: "Dongfeng Dolica D6 | EQ1040S8TD2D | light truck",
    submodelCode: "EQ1040S8TD2D",
    engineModel: "Yuchai YCY24155-61",
    gearboxModel: "FAST 8J45T",
    productBand: "light_truck",
    techStatus: "researched",
    applicableVehicleCodes: "EQ1040S8TD2D",
    applicableMarkets: "中国公开公告 / 轻卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete light-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "360che public listing + domestic replacement mapping",
  },
  {
    cardType: "engine_family",
    brand: "JMC",
    brandCluster: "JMC Kaiyun Plus",
    heroTitle: "JX4D25B6H",
    heroSubtitle: "JMC Kaiyun Plus | JX5049XXYTGA26 | light truck",
    submodelCode: "JX5049XXYTGA26",
    engineModel: "JMC JX4D25B6H",
    gearboxModel: "Wanliyang WLY6G40",
    productBand: "light_truck",
    techStatus: "researched",
    applicableVehicleCodes: "JX5049XXYTGA26",
    applicableMarkets: "中国公开公告 / 轻卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete utility truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "360che public listing + domestic replacement mapping",
  },
  {
    cardType: "engine_family",
    brand: "JMC",
    brandCluster: "JMC Kaiyun Plus",
    heroTitle: "JX4D25B6H",
    heroSubtitle: "JMC Kaiyun Plus | JX5044XXYTGA26 | light truck",
    submodelCode: "JX5044XXYTGA26",
    engineModel: "JMC JX4D25B6H",
    gearboxModel: "Wanliyang WLY6G40",
    productBand: "light_truck",
    techStatus: "researched",
    applicableVehicleCodes: "JX5044XXYTGA26",
    applicableMarkets: "中国公开公告 / 轻卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete utility truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "360che public listing + domestic replacement mapping",
  },
  {
    cardType: "engine_family",
    brand: "JMC",
    brandCluster: "JMC Kaiyun Plus",
    heroTitle: "JX4D25B6H",
    heroSubtitle: "JMC Kaiyun Plus | JX5049XLCTGA26 | light truck",
    submodelCode: "JX5049XLCTGA26",
    engineModel: "JMC JX4D25B6H",
    gearboxModel: "Wanliyang WLY6G40",
    productBand: "light_truck",
    techStatus: "researched",
    applicableVehicleCodes: "JX5049XLCTGA26",
    applicableMarkets: "中国公开公告 / 轻卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete refrigerated truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "360che public listing + domestic replacement mapping",
  },
  {
    cardType: "engine_family",
    brand: "Sinotruk",
    brandCluster: "HOWO Commander",
    heroTitle: "WP2.5NQ180E62",
    heroSubtitle: "HOWO Commander | ZZ5077CCYG3815F174 | light truck",
    submodelCode: "ZZ5077CCYG3815F174",
    engineModel: "Weichai WP2.5NQ180E62",
    gearboxModel: "FAST 8J55TA",
    productBand: "light_truck",
    techStatus: "researched",
    applicableVehicleCodes: "ZZ5077CCYG3815F174",
    applicableMarkets: "中国公开公告 / 轻卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete light-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "360che public listing + domestic replacement mapping",
  },
  {
    cardType: "engine_family",
    brand: "Sinotruk",
    brandCluster: "HOWO Commander",
    heroTitle: "WP2.5NQ180E62",
    heroSubtitle: "HOWO Commander | ZZ5097CCYG3315F191 | light truck",
    submodelCode: "ZZ5097CCYG3315F191",
    engineModel: "Weichai WP2.5NQ180E62",
    gearboxModel: "FAST 8J55TA",
    productBand: "light_truck",
    techStatus: "researched",
    applicableVehicleCodes: "ZZ5097CCYG3315F191",
    applicableMarkets: "中国公开公告 / 轻卡热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from 360che public parameter page",
    imageDirection: "Use engine or complete light-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "360che public listing + domestic replacement mapping",
  },
  {
    cardType: "engine_family",
    brand: "Sinotruk",
    brandCluster: "HOWO Dreamer",
    heroTitle: "WP2.5NQ160E61",
    heroSubtitle: "HOWO Dreamer | ZZ1047G3215F144B | light truck",
    submodelCode: "ZZ1047G3215F144B",
    engineModel: "Weichai WP2.5NQ160E61",
    gearboxModel: "FAST 8J50TA",
    productBand: "light_truck",
    techStatus: "partial",
    applicableVehicleCodes: "ZZ1047G3215F144B",
    applicableMarkets: "中国公开公告 / 经销商热销平台",
    displayPartFamilies: "发动机保养件 / 滤芯保养件",
    trustSignal: "Mapped from public product page and dealer listing with matching announcement code",
    imageDirection: "Use engine or complete light-truck image first; avoid single loose-part image at phase 1",
    contentBlocks: "Hero image / Engine-Gearbox summary / Applicable models / Available part families / Inquiry CTA",
    ctaText: "Send Inquiry for Matching Parts",
    internalDataSource: "dealer listing + domestic replacement mapping",
  },
] as const;

export const productCards: ProductCard[] = rows.map((row) => {
  const heroImage = platformImageMap[row.productBand];
  const dimensions = getImageDimensions(heroImage);

  return {
    ...row,
    applicableVehicleCodes: row.applicableVehicleCodes.split(" / ").filter(Boolean),
    applicableMarkets: row.applicableMarkets.split(" / ").filter(Boolean),
    displayPartFamilies: row.displayPartFamilies.split(" / ").filter(Boolean),
    contentBlocks: row.contentBlocks.split(" / ").filter(Boolean),
    heroImage,
    heroImageAlt: `${row.engineModel || row.heroTitle} platform reference image`,
    heroImageWidth: dimensions.width,
    heroImageHeight: dimensions.height,
  };
});

export const productBrandClusters = [...new Set(productCards.map((item) => item.brandCluster))];
export const productBands = [...new Set(productCards.map((item) => item.productBand))];

export const productStats = {
  totalPlatforms: productCards.length,
  researchedPlatforms: productCards.filter((item) => item.techStatus === "researched").length,
  brandClusters: productBrandClusters.length,
  marketsMentioned: new Set(productCards.flatMap((item) => item.applicableMarkets)).size,
};

export const productReferenceSources = [
  {
    title: "Cummins ISF3.8 engine family",
    type: "Official engine platform page",
    href: "https://www.social.cummins.com/engines/isf38",
    note: "Useful for engine-family validation and future model-specific hero-image capture.",
  },
  {
    title: "ZF EcoLite transmission family",
    type: "Official gearbox platform page",
    href: "https://www.zf.com/products/pl/cv/products_76364.html",
    note: "Supports the gearbox-platform trust layer for light-duty applications.",
  },
  {
    title: "FOTON global product system",
    type: "Official OEM product portal",
    href: "https://www.foton-global.com/products.html",
    note: "Provides brand, vehicle-family, and model-line context for Auman, Aumark, and mini-truck clusters.",
  },
  {
    title: "FOTON Auman super powertrain overview",
    type: "Official OEM overview page",
    href: "https://foton-global.com/aboutUs-3.html",
    note: "Mentions Auman integration with Cummins engines and ZF TraXon gearboxes.",
  },
];

export const productBandLabels: Record<ProductCard["productBand"], string> = {
  light_truck: "Light Truck",
  medium_truck: "Medium Truck",
  heavy_truck: "Heavy Truck",
  mini_truck: "Mini Truck",
};
