export const competitorRows = [
  {
    cardType: 'engine_family',
    brand: 'DFSK',
    brandCluster: 'Xiangling Competitor',
    heroTitle: 'DK12-10',
    heroSubtitle: 'DFSK | K Series | mini_truck',
    submodelCode: 'ENG-DK12-10',
    engineModel: 'DK12-10',
    gearboxModel: '',
    productBand: 'mini_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'K Series',
    applicableMarkets: '危地马拉 / 拉美',
    displayPartFamilies: 'Maintenance Kit / Repair Kit / Replacement Parts',
    trustSignal: 'Public engine platform mapping',
    imageDirection: 'Use engine bay or complete cargo mini-truck image first',
    contentBlocks: 'Hero image / Engine summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'gearbox_family',
    brand: 'DFSK',
    brandCluster: 'Xiangling Competitor',
    heroTitle: 'DFSK 5MT',
    heroSubtitle: 'DFSK | K Series | mini_truck',
    submodelCode: 'GBX-DFSK-5MT',
    engineModel: '',
    gearboxModel: 'DFSK 5MT',
    productBand: 'mini_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'K Series',
    applicableMarkets: '危地马拉 / 拉美',
    displayPartFamilies: 'Repair Kit / Synchronizer Kit / Bearings and Seals',
    trustSignal: 'Public gearbox platform mapping',
    imageDirection: 'Use gearbox or drivetrain image first',
    contentBlocks: 'Hero image / Gearbox summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'axle_family',
    brand: 'DFSK',
    brandCluster: 'Xiangling Competitor',
    heroTitle: 'DFSK Axle System',
    heroSubtitle: 'DFSK | K Series | mini_truck',
    submodelCode: 'AXL-DFSK-K',
    engineModel: '',
    gearboxModel: '',
    productBand: 'mini_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'K Series',
    applicableMarkets: '危地马拉 / 拉美',
    displayPartFamilies: 'Ring and Pinion / Half Shaft / Wheel End Kit',
    trustSignal: 'Sub-brand axle platform grouping',
    imageDirection: 'Use axle assembly or wheel-end image first',
    contentBlocks: 'Hero image / Axle summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'brake_system',
    brand: 'DFSK',
    brandCluster: 'Xiangling Competitor',
    heroTitle: 'DFSK Brake System',
    heroSubtitle: 'DFSK | K Series | mini_truck',
    submodelCode: 'BRK-DFSK-K',
    engineModel: '',
    gearboxModel: '',
    productBand: 'mini_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'K Series',
    applicableMarkets: '危地马拉 / 拉美',
    displayPartFamilies: 'Brake Shoe / Wheel Cylinder / Master Cylinder',
    trustSignal: 'Sub-brand brake platform grouping',
    imageDirection: 'Use brake drum or brake kit image first',
    contentBlocks: 'Hero image / Brake summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'suspension_family',
    brand: 'DFSK',
    brandCluster: 'Xiangling Competitor',
    heroTitle: 'DFSK Suspension System',
    heroSubtitle: 'DFSK | K Series | mini_truck',
    submodelCode: 'SUS-DFSK-K',
    engineModel: '',
    gearboxModel: '',
    productBand: 'mini_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'K Series',
    applicableMarkets: '危地马拉 / 拉美',
    displayPartFamilies: 'Leaf Spring / Shackle Kit / Bushing Kit',
    trustSignal: 'Sub-brand suspension platform grouping',
    imageDirection: 'Use leaf spring or under-chassis image first',
    contentBlocks: 'Hero image / Suspension summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'engine_family',
    brand: 'Wuling',
    brandCluster: 'Xiangling Competitor',
    heroTitle: 'LAR',
    heroSubtitle: 'Wuling | Formo Max | mini_truck',
    submodelCode: 'ENG-LAR',
    engineModel: 'LAR',
    gearboxModel: '',
    productBand: 'mini_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Formo Max',
    applicableMarkets: '印尼 / 东南亚',
    displayPartFamilies: 'Maintenance Kit / Repair Kit / Replacement Parts',
    trustSignal: 'Public engine platform mapping',
    imageDirection: 'Use engine bay or complete vehicle image first',
    contentBlocks: 'Hero image / Engine summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'gearbox_family',
    brand: 'Wuling',
    brandCluster: 'Xiangling Competitor',
    heroTitle: 'Wuling 5MT',
    heroSubtitle: 'Wuling | Formo Max | mini_truck',
    submodelCode: 'GBX-WULING-5MT',
    engineModel: '',
    gearboxModel: 'Wuling 5MT',
    productBand: 'mini_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Formo Max',
    applicableMarkets: '印尼 / 东南亚',
    displayPartFamilies: 'Repair Kit / Synchronizer Kit / Bearings and Seals',
    trustSignal: 'Public gearbox platform mapping',
    imageDirection: 'Use gearbox or drivetrain image first',
    contentBlocks: 'Hero image / Gearbox summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'axle_family',
    brand: 'Wuling',
    brandCluster: 'Xiangling Competitor',
    heroTitle: 'Wuling Axle System',
    heroSubtitle: 'Wuling | Formo Max | mini_truck',
    submodelCode: 'AXL-WULING-FORMO',
    engineModel: '',
    gearboxModel: '',
    productBand: 'mini_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Formo Max',
    applicableMarkets: '印尼 / 东南亚',
    displayPartFamilies: 'Ring and Pinion / Half Shaft / Wheel End Kit',
    trustSignal: 'Sub-brand axle platform grouping',
    imageDirection: 'Use axle assembly or wheel-end image first',
    contentBlocks: 'Hero image / Axle summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'brake_system',
    brand: 'Wuling',
    brandCluster: 'Xiangling Competitor',
    heroTitle: 'Wuling Brake System',
    heroSubtitle: 'Wuling | Formo Max | mini_truck',
    submodelCode: 'BRK-WULING-FORMO',
    engineModel: '',
    gearboxModel: '',
    productBand: 'mini_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Formo Max',
    applicableMarkets: '印尼 / 东南亚',
    displayPartFamilies: 'Brake Shoe / Wheel Cylinder / Master Cylinder',
    trustSignal: 'Sub-brand brake platform grouping',
    imageDirection: 'Use brake drum or brake kit image first',
    contentBlocks: 'Hero image / Brake summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'suspension_family',
    brand: 'Wuling',
    brandCluster: 'Xiangling Competitor',
    heroTitle: 'Wuling Suspension System',
    heroSubtitle: 'Wuling | Formo Max | mini_truck',
    submodelCode: 'SUS-WULING-FORMO',
    engineModel: '',
    gearboxModel: '',
    productBand: 'mini_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Formo Max',
    applicableMarkets: '印尼 / 东南亚',
    displayPartFamilies: 'Leaf Spring / Shackle Kit / Bushing Kit',
    trustSignal: 'Sub-brand suspension platform grouping',
    imageDirection: 'Use leaf spring or under-chassis image first',
    contentBlocks: 'Hero image / Suspension summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'engine_family',
    brand: 'JAC',
    brandCluster: 'Xiangling Competitor',
    heroTitle: 'HFC4GB2.3D',
    heroSubtitle: 'JAC | X200 | mini_truck',
    submodelCode: 'ENG-HFC4GB2.3D',
    engineModel: 'HFC4GB2.3D',
    gearboxModel: '',
    productBand: 'mini_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'X200',
    applicableMarkets: '秘鲁 / 拉美',
    displayPartFamilies: 'Maintenance Kit / Repair Kit / Replacement Parts',
    trustSignal: 'Public engine platform mapping',
    imageDirection: 'Use engine bay or complete X200 image first',
    contentBlocks: 'Hero image / Engine summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'gearbox_family',
    brand: 'JAC',
    brandCluster: 'Xiangling Competitor',
    heroTitle: 'JAC 5MT',
    heroSubtitle: 'JAC | X200 | mini_truck',
    submodelCode: 'GBX-JAC-5MT',
    engineModel: '',
    gearboxModel: 'JAC 5MT',
    productBand: 'mini_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'X200',
    applicableMarkets: '秘鲁 / 拉美',
    displayPartFamilies: 'Repair Kit / Synchronizer Kit / Bearings and Seals',
    trustSignal: 'Public gearbox platform mapping',
    imageDirection: 'Use gearbox or drivetrain image first',
    contentBlocks: 'Hero image / Gearbox summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'axle_family',
    brand: 'JAC',
    brandCluster: 'Xiangling Competitor',
    heroTitle: 'JAC Axle System',
    heroSubtitle: 'JAC | X200 | mini_truck',
    submodelCode: 'AXL-JAC-X200',
    engineModel: '',
    gearboxModel: '',
    productBand: 'mini_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'X200',
    applicableMarkets: '秘鲁 / 拉美',
    displayPartFamilies: 'Ring and Pinion / Half Shaft / Wheel End Kit',
    trustSignal: 'Sub-brand axle platform grouping',
    imageDirection: 'Use axle assembly or wheel-end image first',
    contentBlocks: 'Hero image / Axle summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'brake_system',
    brand: 'JAC',
    brandCluster: 'Xiangling Competitor',
    heroTitle: 'JAC Brake System',
    heroSubtitle: 'JAC | X200 | mini_truck',
    submodelCode: 'BRK-JAC-X200',
    engineModel: '',
    gearboxModel: '',
    productBand: 'mini_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'X200',
    applicableMarkets: '秘鲁 / 拉美',
    displayPartFamilies: 'Brake Shoe / Wheel Cylinder / Master Cylinder',
    trustSignal: 'Sub-brand brake platform grouping',
    imageDirection: 'Use brake drum or brake kit image first',
    contentBlocks: 'Hero image / Brake summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'suspension_family',
    brand: 'JAC',
    brandCluster: 'Xiangling Competitor',
    heroTitle: 'JAC Suspension System',
    heroSubtitle: 'JAC | X200 | mini_truck',
    submodelCode: 'SUS-JAC-X200',
    engineModel: '',
    gearboxModel: '',
    productBand: 'mini_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'X200',
    applicableMarkets: '秘鲁 / 拉美',
    displayPartFamilies: 'Leaf Spring / Shackle Kit / Bushing Kit',
    trustSignal: 'Sub-brand suspension platform grouping',
    imageDirection: 'Use leaf spring or under-chassis image first',
    contentBlocks: 'Hero image / Suspension summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'engine_family',
    brand: 'JAC',
    brandCluster: 'Ollin Competitor',
    heroTitle: 'Cummins ISF3.8',
    heroSubtitle: 'JAC | N-Series | light_truck',
    submodelCode: 'ENG-ISF3.8',
    engineModel: 'Cummins ISF3.8',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'researched',
    applicableVehicleCodes: 'N-Series',
    applicableMarkets: '亚美尼亚 / 中东',
    displayPartFamilies: 'Maintenance Kit / Repair Kit / Replacement Parts',
    trustSignal: 'Official engine platform mapping',
    imageDirection: 'Use engine bay or complete light-truck image first',
    contentBlocks: 'Hero image / Engine summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'gearbox_family',
    brand: 'JAC',
    brandCluster: 'Ollin Competitor',
    heroTitle: 'FAST 8JS75TC',
    heroSubtitle: 'JAC | N-Series | light_truck',
    submodelCode: 'GBX-8JS75TC',
    engineModel: '',
    gearboxModel: 'FAST 8JS75TC',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'N-Series',
    applicableMarkets: '亚美尼亚 / 中东',
    displayPartFamilies: 'Repair Kit / Synchronizer Kit / Bearings and Seals',
    trustSignal: 'Public gearbox platform mapping',
    imageDirection: 'Use gearbox or drivetrain image first',
    contentBlocks: 'Hero image / Gearbox summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'axle_family',
    brand: 'JAC',
    brandCluster: 'Ollin Competitor',
    heroTitle: 'JAC Axle System',
    heroSubtitle: 'JAC | N-Series | light_truck',
    submodelCode: 'AXL-JAC-N',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'N-Series',
    applicableMarkets: '亚美尼亚 / 中东',
    displayPartFamilies: 'Ring and Pinion / Half Shaft / Wheel End Kit',
    trustSignal: 'Sub-brand axle platform grouping',
    imageDirection: 'Use axle assembly or wheel-end image first',
    contentBlocks: 'Hero image / Axle summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'brake_system',
    brand: 'JAC',
    brandCluster: 'Ollin Competitor',
    heroTitle: 'JAC Brake System',
    heroSubtitle: 'JAC | N-Series | light_truck',
    submodelCode: 'BRK-JAC-N',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'N-Series',
    applicableMarkets: '亚美尼亚 / 中东',
    displayPartFamilies: 'Brake Pad / Brake Drum / Master Cylinder',
    trustSignal: 'Sub-brand brake platform grouping',
    imageDirection: 'Use brake drum or brake kit image first',
    contentBlocks: 'Hero image / Brake summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'suspension_family',
    brand: 'JAC',
    brandCluster: 'Ollin Competitor',
    heroTitle: 'JAC Suspension System',
    heroSubtitle: 'JAC | N-Series | light_truck',
    submodelCode: 'SUS-JAC-N',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'N-Series',
    applicableMarkets: '亚美尼亚 / 中东',
    displayPartFamilies: 'Leaf Spring / Shackle Kit / Bushing Kit',
    trustSignal: 'Sub-brand suspension platform grouping',
    imageDirection: 'Use leaf spring or under-chassis image first',
    contentBlocks: 'Hero image / Suspension summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'engine_family',
    brand: 'Isuzu',
    brandCluster: 'Ollin Competitor',
    heroTitle: '4HK1-TCG61',
    heroSubtitle: 'Isuzu | N-Series | light_truck',
    submodelCode: 'ENG-4HK1-TCG61',
    engineModel: '4HK1-TCG61',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'researched',
    applicableVehicleCodes: 'N-Series',
    applicableMarkets: '菲律宾 / 东南亚',
    displayPartFamilies: 'Maintenance Kit / Repair Kit / Replacement Parts',
    trustSignal: 'Official engine platform mapping',
    imageDirection: 'Use engine bay or complete N-Series image first',
    contentBlocks: 'Hero image / Engine summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'gearbox_family',
    brand: 'Isuzu',
    brandCluster: 'Ollin Competitor',
    heroTitle: 'MYY6S',
    heroSubtitle: 'Isuzu | N-Series | light_truck',
    submodelCode: 'GBX-MYY6S',
    engineModel: '',
    gearboxModel: 'MYY6S',
    productBand: 'light_truck',
    techStatus: 'researched',
    applicableVehicleCodes: 'N-Series',
    applicableMarkets: '菲律宾 / 东南亚',
    displayPartFamilies: 'Repair Kit / Synchronizer Kit / Bearings and Seals',
    trustSignal: 'Official gearbox platform mapping',
    imageDirection: 'Use gearbox or drivetrain image first',
    contentBlocks: 'Hero image / Gearbox summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'axle_family',
    brand: 'Isuzu',
    brandCluster: 'Ollin Competitor',
    heroTitle: 'Isuzu Axle System',
    heroSubtitle: 'Isuzu | N-Series | light_truck',
    submodelCode: 'AXL-ISUZU-N',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'N-Series',
    applicableMarkets: '菲律宾 / 东南亚',
    displayPartFamilies: 'Ring and Pinion / Half Shaft / Wheel End Kit',
    trustSignal: 'Sub-brand axle platform grouping',
    imageDirection: 'Use axle assembly or wheel-end image first',
    contentBlocks: 'Hero image / Axle summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'brake_system',
    brand: 'Isuzu',
    brandCluster: 'Ollin Competitor',
    heroTitle: 'Isuzu Brake System',
    heroSubtitle: 'Isuzu | N-Series | light_truck',
    submodelCode: 'BRK-ISUZU-N',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'N-Series',
    applicableMarkets: '菲律宾 / 东南亚',
    displayPartFamilies: 'Brake Pad / Brake Drum / Master Cylinder',
    trustSignal: 'Sub-brand brake platform grouping',
    imageDirection: 'Use brake drum or brake kit image first',
    contentBlocks: 'Hero image / Brake summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'suspension_family',
    brand: 'Isuzu',
    brandCluster: 'Ollin Competitor',
    heroTitle: 'Isuzu Suspension System',
    heroSubtitle: 'Isuzu | N-Series | light_truck',
    submodelCode: 'SUS-ISUZU-N',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'N-Series',
    applicableMarkets: '菲律宾 / 东南亚',
    displayPartFamilies: 'Leaf Spring / Shackle Kit / Bushing Kit',
    trustSignal: 'Sub-brand suspension platform grouping',
    imageDirection: 'Use leaf spring or under-chassis image first',
    contentBlocks: 'Hero image / Suspension summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'engine_family',
    brand: 'Dongfeng',
    brandCluster: 'Ollin Competitor',
    heroTitle: 'YC4F115-50',
    heroSubtitle: 'Dongfeng | Captain T | light_truck',
    submodelCode: 'ENG-YC4F115-50',
    engineModel: 'YC4F115-50',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Captain T',
    applicableMarkets: '海外经销公共平台',
    displayPartFamilies: 'Maintenance Kit / Repair Kit / Replacement Parts',
    trustSignal: 'Public engine platform mapping',
    imageDirection: 'Use engine bay or complete Captain T image first',
    contentBlocks: 'Hero image / Engine summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'gearbox_family',
    brand: 'Dongfeng',
    brandCluster: 'Ollin Competitor',
    heroTitle: '6J45T',
    heroSubtitle: 'Dongfeng | Captain T | light_truck',
    submodelCode: 'GBX-6J45T',
    engineModel: '',
    gearboxModel: '6J45T',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Captain T',
    applicableMarkets: '海外经销公共平台',
    displayPartFamilies: 'Repair Kit / Synchronizer Kit / Bearings and Seals',
    trustSignal: 'Public gearbox platform mapping',
    imageDirection: 'Use gearbox or drivetrain image first',
    contentBlocks: 'Hero image / Gearbox summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'axle_family',
    brand: 'Dongfeng',
    brandCluster: 'Ollin Competitor',
    heroTitle: 'Dongfeng Axle System',
    heroSubtitle: 'Dongfeng | Captain T | light_truck',
    submodelCode: 'AXL-DONGFENG-T',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Captain T',
    applicableMarkets: '海外经销公共平台',
    displayPartFamilies: 'Ring and Pinion / Half Shaft / Wheel End Kit',
    trustSignal: 'Sub-brand axle platform grouping',
    imageDirection: 'Use axle assembly or wheel-end image first',
    contentBlocks: 'Hero image / Axle summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'brake_system',
    brand: 'Dongfeng',
    brandCluster: 'Ollin Competitor',
    heroTitle: 'Dongfeng Brake System',
    heroSubtitle: 'Dongfeng | Captain T | light_truck',
    submodelCode: 'BRK-DONGFENG-T',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Captain T',
    applicableMarkets: '海外经销公共平台',
    displayPartFamilies: 'Brake Pad / Brake Drum / Master Cylinder',
    trustSignal: 'Sub-brand brake platform grouping',
    imageDirection: 'Use brake drum or brake kit image first',
    contentBlocks: 'Hero image / Brake summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'suspension_family',
    brand: 'Dongfeng',
    brandCluster: 'Ollin Competitor',
    heroTitle: 'Dongfeng Suspension System',
    heroSubtitle: 'Dongfeng | Captain T | light_truck',
    submodelCode: 'SUS-DONGFENG-T',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Captain T',
    applicableMarkets: '海外经销公共平台',
    displayPartFamilies: 'Leaf Spring / Shackle Kit / Bushing Kit',
    trustSignal: 'Sub-brand suspension platform grouping',
    imageDirection: 'Use leaf spring or under-chassis image first',
    contentBlocks: 'Hero image / Suspension summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'engine_family',
    brand: 'Hino',
    brandCluster: 'Aumark Competitor',
    heroTitle: 'N04C-WR',
    heroSubtitle: 'Hino | 300 Series | light_truck',
    submodelCode: 'ENG-N04C-WR',
    engineModel: 'N04C-WR',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'researched',
    applicableVehicleCodes: '300 Series',
    applicableMarkets: '菲律宾 / 东南亚',
    displayPartFamilies: 'Maintenance Kit / Repair Kit / Replacement Parts',
    trustSignal: 'Official engine platform mapping',
    imageDirection: 'Use engine bay or complete Hino 300 image first',
    contentBlocks: 'Hero image / Engine summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'gearbox_family',
    brand: 'Hino',
    brandCluster: 'Aumark Competitor',
    heroTitle: 'RE61',
    heroSubtitle: 'Hino | 300 Series | light_truck',
    submodelCode: 'GBX-RE61',
    engineModel: '',
    gearboxModel: 'RE61',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: '300 Series',
    applicableMarkets: '菲律宾 / 东南亚',
    displayPartFamilies: 'Repair Kit / Synchronizer Kit / Bearings and Seals',
    trustSignal: 'Public gearbox platform mapping',
    imageDirection: 'Use gearbox or drivetrain image first',
    contentBlocks: 'Hero image / Gearbox summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'axle_family',
    brand: 'Hino',
    brandCluster: 'Aumark Competitor',
    heroTitle: 'Hino Axle System',
    heroSubtitle: 'Hino | 300 Series | light_truck',
    submodelCode: 'AXL-HINO-300',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: '300 Series',
    applicableMarkets: '菲律宾 / 东南亚',
    displayPartFamilies: 'Ring and Pinion / Half Shaft / Wheel End Kit',
    trustSignal: 'Sub-brand axle platform grouping',
    imageDirection: 'Use axle assembly or wheel-end image first',
    contentBlocks: 'Hero image / Axle summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'brake_system',
    brand: 'Hino',
    brandCluster: 'Aumark Competitor',
    heroTitle: 'Hino Brake System',
    heroSubtitle: 'Hino | 300 Series | light_truck',
    submodelCode: 'BRK-HINO-300',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: '300 Series',
    applicableMarkets: '菲律宾 / 东南亚',
    displayPartFamilies: 'Brake Pad / Brake Drum / Master Cylinder',
    trustSignal: 'Sub-brand brake platform grouping',
    imageDirection: 'Use brake drum or brake kit image first',
    contentBlocks: 'Hero image / Brake summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'suspension_family',
    brand: 'Hino',
    brandCluster: 'Aumark Competitor',
    heroTitle: 'Hino Suspension System',
    heroSubtitle: 'Hino | 300 Series | light_truck',
    submodelCode: 'SUS-HINO-300',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: '300 Series',
    applicableMarkets: '菲律宾 / 东南亚',
    displayPartFamilies: 'Leaf Spring / Shackle Kit / Bushing Kit',
    trustSignal: 'Sub-brand suspension platform grouping',
    imageDirection: 'Use leaf spring or under-chassis image first',
    contentBlocks: 'Hero image / Suspension summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'engine_family',
    brand: 'Isuzu',
    brandCluster: 'Aumark Competitor',
    heroTitle: '4HK1-TCG61',
    heroSubtitle: 'Isuzu | N-Series | light_truck',
    submodelCode: 'ENG-4HK1-OM',
    engineModel: '4HK1-TCG61',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'researched',
    applicableVehicleCodes: 'N-Series',
    applicableMarkets: '菲律宾 / 东南亚',
    displayPartFamilies: 'Maintenance Kit / Repair Kit / Replacement Parts',
    trustSignal: 'Official engine platform mapping',
    imageDirection: 'Use engine bay or complete N-Series image first',
    contentBlocks: 'Hero image / Engine summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'gearbox_family',
    brand: 'Isuzu',
    brandCluster: 'Aumark Competitor',
    heroTitle: 'MYY6S',
    heroSubtitle: 'Isuzu | N-Series | light_truck',
    submodelCode: 'GBX-MYY6S-OM',
    engineModel: '',
    gearboxModel: 'MYY6S',
    productBand: 'light_truck',
    techStatus: 'researched',
    applicableVehicleCodes: 'N-Series',
    applicableMarkets: '菲律宾 / 东南亚',
    displayPartFamilies: 'Repair Kit / Synchronizer Kit / Bearings and Seals',
    trustSignal: 'Official gearbox platform mapping',
    imageDirection: 'Use gearbox or drivetrain image first',
    contentBlocks: 'Hero image / Gearbox summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'axle_family',
    brand: 'Isuzu',
    brandCluster: 'Aumark Competitor',
    heroTitle: 'Isuzu Axle System',
    heroSubtitle: 'Isuzu | N-Series | light_truck',
    submodelCode: 'AXL-ISUZU-OM',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'N-Series',
    applicableMarkets: '菲律宾 / 东南亚',
    displayPartFamilies: 'Ring and Pinion / Half Shaft / Wheel End Kit',
    trustSignal: 'Sub-brand axle platform grouping',
    imageDirection: 'Use axle assembly or wheel-end image first',
    contentBlocks: 'Hero image / Axle summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'brake_system',
    brand: 'Isuzu',
    brandCluster: 'Aumark Competitor',
    heroTitle: 'Isuzu Brake System',
    heroSubtitle: 'Isuzu | N-Series | light_truck',
    submodelCode: 'BRK-ISUZU-OM',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'N-Series',
    applicableMarkets: '菲律宾 / 东南亚',
    displayPartFamilies: 'Brake Pad / Brake Drum / Master Cylinder',
    trustSignal: 'Sub-brand brake platform grouping',
    imageDirection: 'Use brake drum or brake kit image first',
    contentBlocks: 'Hero image / Brake summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'suspension_family',
    brand: 'Isuzu',
    brandCluster: 'Aumark Competitor',
    heroTitle: 'Isuzu Suspension System',
    heroSubtitle: 'Isuzu | N-Series | light_truck',
    submodelCode: 'SUS-ISUZU-OM',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'N-Series',
    applicableMarkets: '菲律宾 / 东南亚',
    displayPartFamilies: 'Leaf Spring / Shackle Kit / Bushing Kit',
    trustSignal: 'Sub-brand suspension platform grouping',
    imageDirection: 'Use leaf spring or under-chassis image first',
    contentBlocks: 'Hero image / Suspension summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'engine_family',
    brand: 'JAC',
    brandCluster: 'Aumark Competitor',
    heroTitle: 'Cummins ISD4.5',
    heroSubtitle: 'JAC | N160 | light_truck',
    submodelCode: 'ENG-ISD4.5',
    engineModel: 'Cummins ISD4.5',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'N160',
    applicableMarkets: '亚美尼亚 / 中东',
    displayPartFamilies: 'Maintenance Kit / Repair Kit / Replacement Parts',
    trustSignal: 'Official engine platform mapping',
    imageDirection: 'Use engine bay or complete larger cargo truck image first',
    contentBlocks: 'Hero image / Engine summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'gearbox_family',
    brand: 'JAC',
    brandCluster: 'Aumark Competitor',
    heroTitle: 'FAST 8JS85E',
    heroSubtitle: 'JAC | N160 | light_truck',
    submodelCode: 'GBX-8JS85E',
    engineModel: '',
    gearboxModel: 'FAST 8JS85E',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'N160',
    applicableMarkets: '亚美尼亚 / 中东',
    displayPartFamilies: 'Repair Kit / Synchronizer Kit / Bearings and Seals',
    trustSignal: 'Public gearbox platform mapping',
    imageDirection: 'Use gearbox or drivetrain image first',
    contentBlocks: 'Hero image / Gearbox summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'axle_family',
    brand: 'JAC',
    brandCluster: 'Aumark Competitor',
    heroTitle: 'JAC Axle System',
    heroSubtitle: 'JAC | N160 | light_truck',
    submodelCode: 'AXL-JAC-N160',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'N160',
    applicableMarkets: '亚美尼亚 / 中东',
    displayPartFamilies: 'Ring and Pinion / Half Shaft / Wheel End Kit',
    trustSignal: 'Sub-brand axle platform grouping',
    imageDirection: 'Use axle assembly or wheel-end image first',
    contentBlocks: 'Hero image / Axle summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'brake_system',
    brand: 'JAC',
    brandCluster: 'Aumark Competitor',
    heroTitle: 'JAC Brake System',
    heroSubtitle: 'JAC | N160 | light_truck',
    submodelCode: 'BRK-JAC-N160',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'N160',
    applicableMarkets: '亚美尼亚 / 中东',
    displayPartFamilies: 'Brake Pad / Brake Drum / Master Cylinder',
    trustSignal: 'Sub-brand brake platform grouping',
    imageDirection: 'Use brake drum or brake kit image first',
    contentBlocks: 'Hero image / Brake summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'suspension_family',
    brand: 'JAC',
    brandCluster: 'Aumark Competitor',
    heroTitle: 'JAC Suspension System',
    heroSubtitle: 'JAC | N160 | light_truck',
    submodelCode: 'SUS-JAC-N160',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'N160',
    applicableMarkets: '亚美尼亚 / 中东',
    displayPartFamilies: 'Leaf Spring / Shackle Kit / Bushing Kit',
    trustSignal: 'Sub-brand suspension platform grouping',
    imageDirection: 'Use leaf spring or under-chassis image first',
    contentBlocks: 'Hero image / Suspension summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'engine_family',
    brand: 'JMC',
    brandCluster: 'Forland Competitor',
    heroTitle: 'JX493ZLQ5',
    heroSubtitle: 'JMC | Carrying Plus | light_truck',
    submodelCode: 'ENG-JX493ZLQ5',
    engineModel: 'JX493ZLQ5',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Carrying Plus',
    applicableMarkets: '沙特 / 中东',
    displayPartFamilies: 'Maintenance Kit / Repair Kit / Replacement Parts',
    trustSignal: 'Official distributor engine platform mapping',
    imageDirection: 'Use engine bay or complete utility truck image first',
    contentBlocks: 'Hero image / Engine summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'gearbox_family',
    brand: 'JMC',
    brandCluster: 'Forland Competitor',
    heroTitle: 'JMC 5MT',
    heroSubtitle: 'JMC | Carrying Plus | light_truck',
    submodelCode: 'GBX-JMC-5MT',
    engineModel: '',
    gearboxModel: 'JMC 5MT',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Carrying Plus',
    applicableMarkets: '沙特 / 中东',
    displayPartFamilies: 'Repair Kit / Synchronizer Kit / Bearings and Seals',
    trustSignal: 'Public gearbox platform mapping',
    imageDirection: 'Use gearbox or drivetrain image first',
    contentBlocks: 'Hero image / Gearbox summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'axle_family',
    brand: 'JMC',
    brandCluster: 'Forland Competitor',
    heroTitle: 'JMC Axle System',
    heroSubtitle: 'JMC | Carrying Plus | light_truck',
    submodelCode: 'AXL-JMC-CARRYING',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Carrying Plus',
    applicableMarkets: '沙特 / 中东',
    displayPartFamilies: 'Ring and Pinion / Half Shaft / Wheel End Kit',
    trustSignal: 'Sub-brand axle platform grouping',
    imageDirection: 'Use axle assembly or wheel-end image first',
    contentBlocks: 'Hero image / Axle summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'brake_system',
    brand: 'JMC',
    brandCluster: 'Forland Competitor',
    heroTitle: 'JMC Brake System',
    heroSubtitle: 'JMC | Carrying Plus | light_truck',
    submodelCode: 'BRK-JMC-CARRYING',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Carrying Plus',
    applicableMarkets: '沙特 / 中东',
    displayPartFamilies: 'Brake Pad / Brake Drum / Master Cylinder',
    trustSignal: 'Sub-brand brake platform grouping',
    imageDirection: 'Use brake drum or brake kit image first',
    contentBlocks: 'Hero image / Brake summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'suspension_family',
    brand: 'JMC',
    brandCluster: 'Forland Competitor',
    heroTitle: 'JMC Suspension System',
    heroSubtitle: 'JMC | Carrying Plus | light_truck',
    submodelCode: 'SUS-JMC-CARRYING',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Carrying Plus',
    applicableMarkets: '沙特 / 中东',
    displayPartFamilies: 'Leaf Spring / Shackle Kit / Bushing Kit',
    trustSignal: 'Sub-brand suspension platform grouping',
    imageDirection: 'Use leaf spring or under-chassis image first',
    contentBlocks: 'Hero image / Suspension summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'engine_family',
    brand: 'Dongfeng',
    brandCluster: 'Forland Competitor',
    heroTitle: 'DK15-06',
    heroSubtitle: 'Dongfeng | Captain W | light_truck',
    submodelCode: 'ENG-DK15-06',
    engineModel: 'DK15-06',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Captain W',
    applicableMarkets: '海外经销公共平台',
    displayPartFamilies: 'Maintenance Kit / Repair Kit / Replacement Parts',
    trustSignal: 'Public engine platform mapping',
    imageDirection: 'Use engine bay or complete Captain W image first',
    contentBlocks: 'Hero image / Engine summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'gearbox_family',
    brand: 'Dongfeng',
    brandCluster: 'Forland Competitor',
    heroTitle: 'Dongfeng 5MT',
    heroSubtitle: 'Dongfeng | Captain W | light_truck',
    submodelCode: 'GBX-DONGFENG-5MT',
    engineModel: '',
    gearboxModel: 'Dongfeng 5MT',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Captain W',
    applicableMarkets: '海外经销公共平台',
    displayPartFamilies: 'Repair Kit / Synchronizer Kit / Bearings and Seals',
    trustSignal: 'Public gearbox platform mapping',
    imageDirection: 'Use gearbox or drivetrain image first',
    contentBlocks: 'Hero image / Gearbox summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'axle_family',
    brand: 'Dongfeng',
    brandCluster: 'Forland Competitor',
    heroTitle: 'Dongfeng Axle System',
    heroSubtitle: 'Dongfeng | Captain W | light_truck',
    submodelCode: 'AXL-DONGFENG-W',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Captain W',
    applicableMarkets: '海外经销公共平台',
    displayPartFamilies: 'Ring and Pinion / Half Shaft / Wheel End Kit',
    trustSignal: 'Sub-brand axle platform grouping',
    imageDirection: 'Use axle assembly or wheel-end image first',
    contentBlocks: 'Hero image / Axle summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'brake_system',
    brand: 'Dongfeng',
    brandCluster: 'Forland Competitor',
    heroTitle: 'Dongfeng Brake System',
    heroSubtitle: 'Dongfeng | Captain W | light_truck',
    submodelCode: 'BRK-DONGFENG-W',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Captain W',
    applicableMarkets: '海外经销公共平台',
    displayPartFamilies: 'Brake Shoe / Wheel Cylinder / Master Cylinder',
    trustSignal: 'Sub-brand brake platform grouping',
    imageDirection: 'Use brake drum or brake kit image first',
    contentBlocks: 'Hero image / Brake summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'suspension_family',
    brand: 'Dongfeng',
    brandCluster: 'Forland Competitor',
    heroTitle: 'Dongfeng Suspension System',
    heroSubtitle: 'Dongfeng | Captain W | light_truck',
    submodelCode: 'SUS-DONGFENG-W',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'Captain W',
    applicableMarkets: '海外经销公共平台',
    displayPartFamilies: 'Leaf Spring / Shackle Kit / Bushing Kit',
    trustSignal: 'Sub-brand suspension platform grouping',
    imageDirection: 'Use leaf spring or under-chassis image first',
    contentBlocks: 'Hero image / Suspension summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'engine_family',
    brand: 'JAC',
    brandCluster: 'Forland Competitor',
    heroTitle: 'HFC4GB2.3D',
    heroSubtitle: 'JAC | X100/X200 | light_truck',
    submodelCode: 'ENG-HFC4GB2.3D-ERA',
    engineModel: 'HFC4GB2.3D',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'X100 / X200',
    applicableMarkets: '拉美 / 中东',
    displayPartFamilies: 'Maintenance Kit / Repair Kit / Replacement Parts',
    trustSignal: 'Public engine platform mapping',
    imageDirection: 'Use engine bay or complete entry truck image first',
    contentBlocks: 'Hero image / Engine summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'gearbox_family',
    brand: 'JAC',
    brandCluster: 'Forland Competitor',
    heroTitle: 'JAC 5MT',
    heroSubtitle: 'JAC | X100/X200 | light_truck',
    submodelCode: 'GBX-JAC-5MT-ERA',
    engineModel: '',
    gearboxModel: 'JAC 5MT',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'X100 / X200',
    applicableMarkets: '拉美 / 中东',
    displayPartFamilies: 'Repair Kit / Synchronizer Kit / Bearings and Seals',
    trustSignal: 'Public gearbox platform mapping',
    imageDirection: 'Use gearbox or drivetrain image first',
    contentBlocks: 'Hero image / Gearbox summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'axle_family',
    brand: 'JAC',
    brandCluster: 'Forland Competitor',
    heroTitle: 'JAC Axle System',
    heroSubtitle: 'JAC | X100/X200 | light_truck',
    submodelCode: 'AXL-JAC-ERA',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'X100 / X200',
    applicableMarkets: '拉美 / 中东',
    displayPartFamilies: 'Ring and Pinion / Half Shaft / Wheel End Kit',
    trustSignal: 'Sub-brand axle platform grouping',
    imageDirection: 'Use axle assembly or wheel-end image first',
    contentBlocks: 'Hero image / Axle summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'brake_system',
    brand: 'JAC',
    brandCluster: 'Forland Competitor',
    heroTitle: 'JAC Brake System',
    heroSubtitle: 'JAC | X100/X200 | light_truck',
    submodelCode: 'BRK-JAC-ERA',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'X100 / X200',
    applicableMarkets: '拉美 / 中东',
    displayPartFamilies: 'Brake Shoe / Wheel Cylinder / Master Cylinder',
    trustSignal: 'Sub-brand brake platform grouping',
    imageDirection: 'Use brake drum or brake kit image first',
    contentBlocks: 'Hero image / Brake summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'suspension_family',
    brand: 'JAC',
    brandCluster: 'Forland Competitor',
    heroTitle: 'JAC Suspension System',
    heroSubtitle: 'JAC | X100/X200 | light_truck',
    submodelCode: 'SUS-JAC-ERA',
    engineModel: '',
    gearboxModel: '',
    productBand: 'light_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'X100 / X200',
    applicableMarkets: '拉美 / 中东',
    displayPartFamilies: 'Leaf Spring / Shackle Kit / Bushing Kit',
    trustSignal: 'Sub-brand suspension platform grouping',
    imageDirection: 'Use leaf spring or under-chassis image first',
    contentBlocks: 'Hero image / Suspension summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'engine_family',
    brand: 'Sinotruk',
    brandCluster: 'Auman Competitor',
    heroTitle: 'MC11.44-50',
    heroSubtitle: 'Sinotruk | HOWO-TX | heavy_truck',
    submodelCode: 'ENG-MC11.44-50',
    engineModel: 'MC11.44-50',
    gearboxModel: '',
    productBand: 'heavy_truck',
    techStatus: 'researched',
    applicableVehicleCodes: 'HOWO-TX',
    applicableMarkets: '国际重卡渠道',
    displayPartFamilies: 'Maintenance Kit / Repair Kit / Replacement Parts',
    trustSignal: 'Official heavy-truck engine platform mapping',
    imageDirection: 'Use engine bay or complete tractor-truck image first',
    contentBlocks: 'Hero image / Engine summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'gearbox_family',
    brand: 'Sinotruk',
    brandCluster: 'Auman Competitor',
    heroTitle: 'HW19712CL',
    heroSubtitle: 'Sinotruk | HOWO-TX | heavy_truck',
    submodelCode: 'GBX-HW19712CL',
    engineModel: '',
    gearboxModel: 'HW19712CL',
    productBand: 'heavy_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'HOWO-TX',
    applicableMarkets: '国际重卡渠道',
    displayPartFamilies: 'Repair Kit / Synchronizer Kit / Bearings and Seals',
    trustSignal: 'Public heavy-truck gearbox platform mapping',
    imageDirection: 'Use gearbox or drivetrain image first',
    contentBlocks: 'Hero image / Gearbox summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'axle_family',
    brand: 'Sinotruk',
    brandCluster: 'Auman Competitor',
    heroTitle: 'HOWO-TX Axle System',
    heroSubtitle: 'Sinotruk | HOWO-TX | heavy_truck',
    submodelCode: 'AXL-HOWOTX',
    engineModel: '',
    gearboxModel: '',
    productBand: 'heavy_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'HOWO-TX',
    applicableMarkets: '国际重卡渠道',
    displayPartFamilies: 'Ring and Pinion / Half Shaft / Wheel End Kit',
    trustSignal: 'Sub-brand axle platform grouping',
    imageDirection: 'Use axle assembly or wheel-end image first',
    contentBlocks: 'Hero image / Axle summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'brake_system',
    brand: 'Sinotruk',
    brandCluster: 'Auman Competitor',
    heroTitle: 'HOWO-TX Brake System',
    heroSubtitle: 'Sinotruk | HOWO-TX | heavy_truck',
    submodelCode: 'BRK-HOWOTX',
    engineModel: '',
    gearboxModel: '',
    productBand: 'heavy_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'HOWO-TX',
    applicableMarkets: '国际重卡渠道',
    displayPartFamilies: 'Brake Lining / Air Brake Valve / Chamber Kit',
    trustSignal: 'Sub-brand brake platform grouping',
    imageDirection: 'Use brake kit or valve image first',
    contentBlocks: 'Hero image / Brake summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'suspension_family',
    brand: 'Sinotruk',
    brandCluster: 'Auman Competitor',
    heroTitle: 'HOWO-TX Suspension System',
    heroSubtitle: 'Sinotruk | HOWO-TX | heavy_truck',
    submodelCode: 'SUS-HOWOTX',
    engineModel: '',
    gearboxModel: '',
    productBand: 'heavy_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'HOWO-TX',
    applicableMarkets: '国际重卡渠道',
    displayPartFamilies: 'Leaf Spring / Torque Rod Bushing / Shock Absorber',
    trustSignal: 'Sub-brand suspension platform grouping',
    imageDirection: 'Use suspension linkage or under-chassis image first',
    contentBlocks: 'Hero image / Suspension summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'engine_family',
    brand: 'SHACMAN',
    brandCluster: 'Auman Competitor',
    heroTitle: 'WP12.430E50',
    heroSubtitle: 'SHACMAN | X3000 | heavy_truck',
    submodelCode: 'ENG-WP12.430E50',
    engineModel: 'WP12.430E50',
    gearboxModel: '',
    productBand: 'heavy_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'X3000 / F3000',
    applicableMarkets: '国际重卡渠道',
    displayPartFamilies: 'Maintenance Kit / Repair Kit / Replacement Parts',
    trustSignal: 'Public heavy-truck engine platform mapping',
    imageDirection: 'Use engine bay or complete tractor image first',
    contentBlocks: 'Hero image / Engine summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'gearbox_family',
    brand: 'SHACMAN',
    brandCluster: 'Auman Competitor',
    heroTitle: 'FAST 12JSDX220TA',
    heroSubtitle: 'SHACMAN | X3000 | heavy_truck',
    submodelCode: 'GBX-12JSDX220TA',
    engineModel: '',
    gearboxModel: 'FAST 12JSDX220TA',
    productBand: 'heavy_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'X3000 / F3000',
    applicableMarkets: '国际重卡渠道',
    displayPartFamilies: 'Repair Kit / Synchronizer Kit / Bearings and Seals',
    trustSignal: 'Public heavy-truck gearbox platform mapping',
    imageDirection: 'Use gearbox or drivetrain image first',
    contentBlocks: 'Hero image / Gearbox summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'axle_family',
    brand: 'SHACMAN',
    brandCluster: 'Auman Competitor',
    heroTitle: 'SHACMAN Axle System',
    heroSubtitle: 'SHACMAN | X3000 | heavy_truck',
    submodelCode: 'AXL-SHACMAN-X3000',
    engineModel: '',
    gearboxModel: '',
    productBand: 'heavy_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'X3000 / F3000',
    applicableMarkets: '国际重卡渠道',
    displayPartFamilies: 'Ring and Pinion / Half Shaft / Wheel End Kit',
    trustSignal: 'Sub-brand axle platform grouping',
    imageDirection: 'Use axle assembly or wheel-end image first',
    contentBlocks: 'Hero image / Axle summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'brake_system',
    brand: 'SHACMAN',
    brandCluster: 'Auman Competitor',
    heroTitle: 'SHACMAN Brake System',
    heroSubtitle: 'SHACMAN | X3000 | heavy_truck',
    submodelCode: 'BRK-SHACMAN-X3000',
    engineModel: '',
    gearboxModel: '',
    productBand: 'heavy_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'X3000 / F3000',
    applicableMarkets: '国际重卡渠道',
    displayPartFamilies: 'Brake Lining / Air Brake Valve / Chamber Kit',
    trustSignal: 'Sub-brand brake platform grouping',
    imageDirection: 'Use brake kit or valve image first',
    contentBlocks: 'Hero image / Brake summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'suspension_family',
    brand: 'SHACMAN',
    brandCluster: 'Auman Competitor',
    heroTitle: 'SHACMAN Suspension System',
    heroSubtitle: 'SHACMAN | X3000 | heavy_truck',
    submodelCode: 'SUS-SHACMAN-X3000',
    engineModel: '',
    gearboxModel: '',
    productBand: 'heavy_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'X3000 / F3000',
    applicableMarkets: '国际重卡渠道',
    displayPartFamilies: 'Leaf Spring / Torque Rod Bushing / Shock Absorber',
    trustSignal: 'Sub-brand suspension platform grouping',
    imageDirection: 'Use suspension linkage or under-chassis image first',
    contentBlocks: 'Hero image / Suspension summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'engine_family',
    brand: 'FAW',
    brandCluster: 'Auman Competitor',
    heroTitle: 'CA6DM2-46E52',
    heroSubtitle: 'FAW | J6P | heavy_truck',
    submodelCode: 'ENG-CA6DM2-46E52',
    engineModel: 'CA6DM2-46E52',
    gearboxModel: '',
    productBand: 'heavy_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'J6P',
    applicableMarkets: '中国一汽国际重卡渠道',
    displayPartFamilies: 'Maintenance Kit / Repair Kit / Replacement Parts',
    trustSignal: 'Official heavy-truck engine platform mapping',
    imageDirection: 'Use engine bay or complete FAW heavy-truck image first',
    contentBlocks: 'Hero image / Engine summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'gearbox_family',
    brand: 'FAW',
    brandCluster: 'Auman Competitor',
    heroTitle: 'CA12TAX210M',
    heroSubtitle: 'FAW | J6P | heavy_truck',
    submodelCode: 'GBX-CA12TAX210M',
    engineModel: '',
    gearboxModel: 'CA12TAX210M',
    productBand: 'heavy_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'J6P',
    applicableMarkets: '中国一汽国际重卡渠道',
    displayPartFamilies: 'Repair Kit / Synchronizer Kit / Bearings and Seals',
    trustSignal: 'Public heavy-truck gearbox platform mapping',
    imageDirection: 'Use gearbox or drivetrain image first',
    contentBlocks: 'Hero image / Gearbox summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_export_model_table_9 + assembly optimization',
  },
  {
    cardType: 'axle_family',
    brand: 'FAW',
    brandCluster: 'Auman Competitor',
    heroTitle: 'FAW Axle System',
    heroSubtitle: 'FAW | J6P | heavy_truck',
    submodelCode: 'AXL-FAW-J6P',
    engineModel: '',
    gearboxModel: '',
    productBand: 'heavy_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'J6P',
    applicableMarkets: '中国一汽国际重卡渠道',
    displayPartFamilies: 'Ring and Pinion / Half Shaft / Wheel End Kit',
    trustSignal: 'Sub-brand axle platform grouping',
    imageDirection: 'Use axle assembly or wheel-end image first',
    contentBlocks: 'Hero image / Axle summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'brake_system',
    brand: 'FAW',
    brandCluster: 'Auman Competitor',
    heroTitle: 'FAW Brake System',
    heroSubtitle: 'FAW | J6P | heavy_truck',
    submodelCode: 'BRK-FAW-J6P',
    engineModel: '',
    gearboxModel: '',
    productBand: 'heavy_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'J6P',
    applicableMarkets: '中国一汽国际重卡渠道',
    displayPartFamilies: 'Brake Lining / Air Brake Valve / Chamber Kit',
    trustSignal: 'Sub-brand brake platform grouping',
    imageDirection: 'Use brake kit or valve image first',
    contentBlocks: 'Hero image / Brake summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
  {
    cardType: 'suspension_family',
    brand: 'FAW',
    brandCluster: 'Auman Competitor',
    heroTitle: 'FAW Suspension System',
    heroSubtitle: 'FAW | J6P | heavy_truck',
    submodelCode: 'SUS-FAW-J6P',
    engineModel: '',
    gearboxModel: '',
    productBand: 'heavy_truck',
    techStatus: 'partial',
    applicableVehicleCodes: 'J6P',
    applicableMarkets: '中国一汽国际重卡渠道',
    displayPartFamilies: 'Leaf Spring / Torque Rod Bushing / Shock Absorber',
    trustSignal: 'Sub-brand suspension platform grouping',
    imageDirection: 'Use suspension linkage or under-chassis image first',
    contentBlocks: 'Hero image / Suspension summary / Applicable series / Inquiry CTA',
    ctaText: 'Send Inquiry for Matching Parts',
    internalDataSource: 'competitor_parts_direction_table_10 + assembly optimization',
  },
] as const;
